name: cs231n_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=11.8  # check CUDA 
  - transformers
  - pandas
  - pillow
  - numpy=1.26.4
  - tqdm
  - opencv
  - tensorboard


  #On the VM use the following command: conda activate /opt/dlami/nvme/miniconda3/envs/cs231n_project